export const routers = Object.freeze({
  CREATERADIO: "createaudio",
  CREATECLIP: "createclip",
  MODIRADIO: "modifyaudio",
  MODICLIP: "modifyclip",
  SELECTLOGIN: "selectlogin",
  EMAILLOGIN: "maillogin",
  SIGNUP: "signup",
  PROFILE: "profile/:id",
  CLIPPLAY: "clipplay/:id",
  TAG: "tag/:id",
  SEARCH: "search",
  KAKAORE: "/login/oauth2/code/kakao",
  NAVERRE: "/login/oauth2/code/naver",
  MYALARM: "alarm/:id",
  MYALBUM: "album/:id",
  ALLVIEWAUDIOCLIP: "allclips/:id",
});
